defaults: &defaults
  technorati_api_key: xxx
  daylife_access_key: xxx
  daylife_secret: xxx
  twitter_consumer: xxx
  twitter_secret: xxx
  sunlightlabs_key: abd6701acbdd4acaac4781db70c455b0
  maplight:  e5ab2775f9d10e9bbff3408d4873ae45
  wiki_pass: xxx
  wiki_key: xxx
  wiki_callback_key: xx
  app_key: xxx
  yahoo_apis: xxx
  civicrm_system_key: xxx
  civicrm_user_key: xxx
  project_vote_smart: xxx
  google_maps: xxx
  airbrake: xxx
  bitly: xxx
  aws_access_key_id: xxx
  aws_secret_access_key: xxx
  formageddon_password: xxx
  formageddon_get_replies_key: xxx
  bing: xxx
  defensio: xxx
  
development:
  <<: *defaults
  
test:
  <<: *defaults

staging:
  <<: *defaults
  
production:
  <<: *defaults

drm:
  <<: *defaults
