development:
  app_id: id
  app_secret: secret
  api_key: xxx
  callback_url: xxx


staging:
  app_id: id
  app_secret: secret
  api_key: xxx
  callback_url: xxx

production:
  app_id: id
  app_secret: secret
  api_key: xxx
  callback_url: xxx
test:
  app_id: id
  app_secret: secret
  api_key: xxx
  callback_url: xxx
drm:
  app_id: id
  app_secret: secret
  api_key: xxx
  callback_url: xxx
